name: Redeploy Architecture PROD

on:
  push:
    branches:
      - main

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.PROD_IP }} >> ~/.ssh/known_hosts

      - name: Redeploy Architecture
        run: |
          ssh ingsisAHRE@${{ secrets.PROD_IP }} << 'EOF'
            cd snippetInfra
            sudo su
            git pull
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml up -d --remove-orphans
            docker image prune -a -f
            docker volume prune -f          
          EOF
